export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_ERROR = 'FETCH_AUTHORS_ERROR';
export const SET_ACTIVE_AUTHOR = 'SET_ACTIVE_AUTHOR';
